### ISSUE TITLE
Current Docker API not supported

### ISSUE THREAD

**Issue by mgns** [Dockerizing/dockerizing-bootstrap#8]
Using a current Docker API (1.30) the python libs (https://github.com/Dockerizing/baselibs) not gonna work. 

```
Traceback (most recent call last):
  File "/dld/dld.py", line 366, in <module>
    main()
  File "/dld/dld.py", line 299, in main
    from config import DLDConfig
  File "/dld/config.py", line 12, in <module>
    class DLDConfig(object):
  File "/dld/config.py", line 51, in DLDConfig
    with dockerutil.docker_client() as dc:
  File "/dld/baselibs/python/dldbase/dockerutil.py", line 29, in __enter__
    err_repr=explanation or repr(e)))
docker.errors.DockerException: Encountered problem when interacting with your Docker Engine:
ConnectionError(ProtocolError('Connection aborted.', FileNotFoundError(2, 'No such file or directory')),)
 * Is the Docker Daemon up and running?
 * Does the daemon use TLS? (currently unsupported by this tool)
```

**Comment by white-gecko** [comment]
Ok, the is a new version available: https://pypi.python.org/pypi/docker so we should update this: https://github.com/docker/docker-py/issues/1431
